const topics=["Все темы","Логика и теория","Алгоритмы","Данные и файлы","Графы и сети"];
const tasks=[
{n:1,t:"Графы и таблицы дорог",g:"Графы и сети",p:"Даны дороги с длинами: A–B = 2, B–C = 3, C–D = 2, A–C = 10, B–D = 8. Найди кратчайшее расстояние из A в D.",a:"7",h:"Сравни прямые маршруты и маршруты с промежуточными городами. Длина пути — сумма длин его рёбер.",s:"A–B–C–D: 2 + 3 + 2 = 7. Другие маршруты длиннее.",c:"Граф можно хранить как список рёбер или словарь соседей. Для такого маленького графа перебери пути; для больших используй Дейкстру."},
{n:2,t:"Таблицы истинности",g:"Логика и теория",p:"Для скольких наборов (x,y) выражение «истинно ровно одно из двух» истинно? x и y — логические переменные.",a:"2",h:"Запиши четыре пары: 00, 01, 10, 11.",s:"Подходят 01 и 10: ответ 2. Это исключающее ИЛИ (XOR).",c:"Перебери product([0,1], repeat=2), оставь пары, где x != y."},
{n:3,t:"Базы данных и запросы",g:"Данные и файлы",p:"В таблице: Анна — 5 решённых задач, Борис — 8, Вера — 6, Глеб — 8. Сколько учеников решили не меньше 6 задач?",a:"3",h:"«Не меньше 6» означает ≥ 6. Проверь каждую запись один раз.",s:"Борис, Вера и Глеб: всего 3 ученика.",c:"В SQL это SELECT COUNT(*) FROM results WHERE solved >= 6; в Python — sum(x >= 6 for x in values)."},
{n:4,t:"Кодирование и условие Фано",g:"Логика и теория",p:"Есть кодовые слова 0, 10, 110 и 1110. Какое кратчайшее двоичное слово длины не более 4 можно добавить, чтобы сохранилось условие Фано?",a:"1111",h:"Ни одно слово не должно быть началом другого. Сначала проверь короткие слова и все уже занятые префиксы.",s:"0 и 10 заняты как префиксы; ветвь 110 тоже занята. 1110 занято целиком, а 1111 свободно. Ответ 1111.",c:"Проверяй кандидата c против каждого существующего w: не должно быть c.startswith(w) или w.startswith(c)."},
{n:5,t:"Преобразование числа",g:"Алгоритмы",p:"Алгоритм заменяет число n на 2n + 1. Начни с 3 и выполни три шага. Какое число получится?",a:"31",h:"Выпиши значения после каждого шага: n₀=3, n₁=2n₀+1 и так далее.",s:"3 → 7 → 15 → 31.",c:"for _ in range(3): n = 2*n + 1"},
{n:6,t:"Исполнители и координаты",g:"Алгоритмы",p:"Исполнитель стартует в (0, 0). Команды: вправо на 4, вверх на 3, влево на 2. Какова конечная координата? Ответ запиши как x,y.",a:"2,3",h:"Изменяй отдельно x и y. Влево уменьшает x, вверх увеличивает y.",s:"x = 0 + 4 − 2 = 2; y = 0 + 3 = 3.",c:"x, y = 0, 0; x += 4; y += 3; x -= 2"},
{n:7,t:"Объём изображения и звука",g:"Логика и теория",p:"Изображение имеет размер 320 × 200 пикселей и палитру из 16 цветов. Сколько бит нужно для хранения без сжатия?",a:"256000",h:"16 цветов требуют 4 бита на пиксель, потому что 2⁴ = 16.",s:"320 × 200 × 4 = 256 000 бит.",c:"bits = width * height * ceil(log2(colors))"},
{n:8,t:"Комбинаторика",g:"Логика и теория",p:"Сколькими способами можно расставить на полке 5 разных книг?",a:"120",h:"Все книги разные и порядок важен. Переставляются все 5 объектов.",s:"5! = 5×4×3×2×1 = 120.",c:"import math; answer = math.factorial(5)"},
{n:9,t:"Электронные таблицы",g:"Данные и файлы",p:"В столбце записаны значения: 12, 8, 15, 9, 20, 11. Сколько значений лежит в диапазоне от 10 до 15 включительно?",a:"3",h:"Проверь границы: 10 ≤ x ≤ 15. Значения 10 и 15 тоже включаются.",s:"Подходят 12, 15 и 11. Ответ 3.",c:"sum(10 <= x <= 15 for x in values)"},
{n:10,t:"IP-адрес и маска",g:"Графы и сети",p:"IP-адрес 192.168.7.130 задан с маской 255.255.255.192. Найди адрес сети и запиши сумму его октетов.",a:"495",h:"В последнем октете маска 192 делит адреса на блоки по 64: 0–63, 64–127, 128–191, 192–255.",s:"130 находится в диапазоне 128–191, значит адрес сети 192.168.7.128. Сумма: 192+168+7+128 = 495.",c:"import ipaddress; net = ipaddress.ip_network('192.168.7.130/255.255.255.192', strict=False); answer = sum(map(int, str(net.network_address).split('.')))"},
{n:11,t:"Количество информации",g:"Логика и теория",p:"Сообщение состоит из 32 символов алфавита из 32 равновероятных знаков. Сколько бит информации в сообщении?",a:"160",h:"Один символ несёт log₂(32)=5 бит.",s:"32 символа × 5 бит = 160 бит.",c:"bits = length * math.log2(alphabet_size)"},
{n:12,t:"Строковый исполнитель",g:"Алгоритмы",p:"Пока в строке есть «11», исполнитель заменяет самое левое вхождение «11» на «2». Сколько замен будет для строки 111111?",a:"3",h:"После каждого шага заново найди самое левое «11». Не заменяй все пары одновременно.",s:"111111 → 21111 → 2211 → 222. Выполнено 3 замены.",c:"while '11' in s: s = s.replace('11', '2', 1); count += 1"},
{n:13,t:"Подсчёт программ исполнителя",g:"Алгоритмы",p:"Исполнитель из числа n делает одну из команд: +1 или +2. Сколько разных программ переводят 1 в 5? Повторять команды можно.",a:"5",h:"Число программ для n получается сложением числа программ, ведущих в n−1 и n−2.",s:"dp[1]=1, dp[2]=1, dp[3]=2, dp[4]=3, dp[5]=5.",c:"dp = [0]*6; dp[1] = 1\nfor n in range(2, 6): dp[n] = dp[n-1] + (dp[n-2] if n >= 3 else 0)"},
{n:14,t:"Системы счисления",g:"Логика и теория",p:"Переведи двоичное число 101101₂ в десятичную систему.",a:"45",h:"Разложи по степеням двойки, справа налево начиная с 2⁰.",s:"32 + 8 + 4 + 1 = 45.",c:"int('101101', 2)"},
{n:15,t:"Логические выражения с параметром",g:"Логика и теория",p:"Сколько целых x от 0 до 9 включительно удовлетворяют условию x < 3 ИЛИ x > 6?",a:"6",h:"Раздели множество на две непересекающиеся части: меньше 3 и больше 6.",s:"Подходят 0,1,2 и 7,8,9. Всего 6.",c:"sum(x < 3 or x > 6 for x in range(10))"},
{n:16,t:"Рекуррентные выражения",g:"Алгоритмы",p:"Дано F₀=1, F₁=2, Fₙ=2Fₙ₋₁+Fₙ₋₂. Найди F₅.",a:"70",h:"Вычисляй последовательно и записывай оба предыдущих значения.",s:"F₂=5, F₃=12, F₄=29, F₅=70.",c:"f = [1, 2]\nfor n in range(2, 6): f.append(2*f[-1] + f[-2])"},
{n:17,t:"Числовая последовательность из файла",g:"Данные и файлы",p:"Последовательность: 6, 12, 9, 15, 10. Сколько соседних пар имеют сумму, кратную 3?",a:"3",h:"Рассмотри пары (6,12), (12,9), (9,15), (15,10). Соседство важно.",s:"Суммы: 18, 21, 24, 25. Первые три кратны 3, ответ 3.",c:"sum((a+b) % 3 == 0 for a,b in zip(data, data[1:]))"},
{n:18,t:"Динамика по клеткам",g:"Алгоритмы",p:"Робот идёт только вправо или вниз по таблице 2×2: верхний ряд 1, 5; нижний ряд 3, 2. Какова максимальная сумма чисел на пути из левой верхней в правую нижнюю клетку?",a:"8",h:"Есть два пути: через 5 или через 3. Включай и стартовую, и финишную клетки.",s:"Путь вправо-вниз: 1+5+2=8; вниз-вправо: 1+3+2=6. Максимум 8.",c:"dp[i][j] = grid[i][j] + max(dp[i-1][j], dp[i][j-1])"},
{n:19,t:"Игра: выигрыш первым ходом",g:"Логика и теория",p:"В куче 10 камней. За ход можно добавить 1 или 3 камня. Побеждает тот, после чьего хода стало не меньше 13. Может ли первый игрок выиграть первым ходом?",a:"да",h:"Проверь, существует ли одна команда, которая сразу достигает 13 или больше.",s:"Да: первый игрок добавляет 3 и получает 13.",c:"any(s + move >= target for move in moves)"},
{n:20,t:"Игра: найти выигрышный ответ",g:"Логика и теория",p:"После хода соперника в куче 6 камней. Сейчас твой ход; можно добавить 1 или 2. Победа наступает при 8 камнях или больше. Какой ход гарантирует победу прямо сейчас?",a:"+2",h:"Проверь результат каждой разрешённой команды.",s:"Нужно добавить 2: получится 8 и условие победы выполнено.",c:"winning_moves = [m for m in moves if s + m >= target]"},
{n:21,t:"Игра: стратегия на несколько ходов",g:"Логика и теория",p:"В куче 5 камней. Игроки по очереди добавляют 1 или 2. Победа — получить не меньше 10. Какой первый ход гарантирует победу первому игроку на его следующем ходу, даже если соперник отвечает оптимально?",a:"+2",h:"После первого хода оставь сопернику 7. Тогда после его ответа останется 8 или 9, и можно добрать до 10.",s:"Первым ходом +2: станет 7. Соперник сделает 8 или 9. Затем +2 выигрывает в обоих случаях.",c:"Перебери первый ход, затем все ответы соперника (all), затем существующий ответ игрока (any)."},
{n:22,t:"Параллельные процессы",g:"Алгоритмы",p:"Работы A и B идут параллельно и занимают 3 и 5 минут. Работа C длится 4 минуты и начинается только после завершения обеих. За сколько минут закончатся все работы?",a:"9",h:"A и B идут одновременно, значит к C переходят после более долгой работы.",s:"C начнётся через max(3,5)=5 минут. 5+4=9 минут.",c:"finish_C = max(finish_A, finish_B) + duration_C"},
{n:23,t:"Графы: кратчайший путь",g:"Графы и сети",p:"Рёбра ориентированного графа имеют длины: A→B 4, A→C 2, C→B 1, B→D 3, C→D 9. Найди длину кратчайшего пути A→D.",a:"6",h:"Сравни маршруты A→B→D и A→C→B→D, а также A→C→D.",s:"A→C→B→D имеет длину 2+1+3=6, это кратчайший путь.",c:"Дейкстра для весов ≥ 0; для маленького DAG можно перебрать пути или посчитать динамикой."},
{n:24,t:"Обработка строк",g:"Алгоритмы",p:"Найди длину самой длинной подряд идущей серии символов A в строке ABAAABBBA.",a:"3",h:"Считай текущую серию одинаковых символов; сбрасывай счётчик на другом символе.",s:"Самая длинная серия — AAA, её длина 3.",c:"current = best = 0\nfor ch in s:\n    current = current + 1 if ch == 'A' else 0\n    best = max(best, current)"},
{n:25,t:"Делители числа",g:"Алгоритмы",p:"Сколько положительных делителей у числа 36?",a:"9",h:"Делители удобно искать парами до √36=6.",s:"Делители: 1,2,3,4,6,9,12,18,36. Всего 9.",c:"sum(36 % d == 0 for d in range(1, 37))"},
{n:26,t:"Интервалы и жадный выбор",g:"Данные и файлы",p:"Нужно выбрать максимум непересекающихся занятий; завершение ровно в момент начала следующего разрешено. Интервалы: [1,3], [2,4], [3,5], [5,7]. Сколько занятий можно выбрать?",a:"3",h:"Отсортируй по времени завершения и каждый раз выбирай самое раннее совместимое занятие.",s:"Берём [1,3], [3,5], [5,7]. Можно выбрать 3 занятия.",c:"events.sort(key=lambda e: e[1]); выбери интервал, если start >= finish_last"},
{n:27,t:"Кластеры точек",g:"Данные и файлы",p:"Четыре точки образуют две явно разделённые группы: (0,0), (0,2) и (10,10), (10,12). Сколько точек в самом большом кластере?",a:"2",h:"Посчитай элементы в каждой из двух групп.",s:"В каждом кластере по 2 точки. Размер самого большого кластера — 2.",c:"Для файловых кластеров строй граф близости точек, ищи компоненты связности и считай элементы в каждой компоненте."}
];

const key='egeProgress2027-v1';
let state=loadState(); let activeFilter='Все темы'; let activeTask=1; let teacherMode=false;
function loadState(){try{return JSON.parse(localStorage.getItem(key))||{tasks:{},note:''}}catch{return {tasks:{},note:''}}}
function save(){localStorage.setItem(key,JSON.stringify(state));renderStats();renderList();if(document.querySelector('#progress-view').classList.contains('hidden')===false)renderProgress()}
function normalize(s){return String(s??'').trim().toLowerCase().replace(/[₀₁₂₃₄₅₆₇₈₉]/g,'').replace(/\s+/g,'').replace(/,/g,',').replace(/ё/g,'е')}
function record(n){return state.tasks[n]||(state.tasks[n]={attempts:0,correct:false,confidence:'',verified:false,note:''})}
function renderStats(){const vals=Object.values(state.tasks);const viewed=vals.filter(v=>v.attempts||v.confidence||v.verified).length;const correct=vals.filter(v=>v.correct).length;const independent=vals.filter(v=>v.confidence==='independent').length;const review=vals.filter(v=>v.confidence==='review').length;document.querySelector('#stat-viewed').innerHTML=`${viewed} <small>/ 27</small>`;document.querySelector('#stat-correct').textContent=correct;document.querySelector('#stat-independent').textContent=independent;document.querySelector('#stat-review').textContent=review;document.querySelector('#hero-done').textContent=viewed;document.querySelector('#hero-independent').textContent=`${independent} уверенно`;document.querySelector('#hero-needs').textContent=`${review} повторить`;document.querySelector('#hero-bar').style.width=`${viewed/27*100}%`}
function renderFilters(){document.querySelector('#filters').innerHTML=topics.map(t=>`<button class="filter ${t===activeFilter?'active':''}" data-filter="${t}">${t}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;renderFilters();renderList()})}
function visibleTasks(){const q=document.querySelector('#search').value.trim().toLowerCase();return tasks.filter(t=>(activeFilter==='Все темы'||t.g===activeFilter)&&(!q||`${t.n} ${t.t} ${t.g}`.toLowerCase().includes(q)))}
function renderList(){const list=document.querySelector('#task-list');list.innerHTML=visibleTasks().map(t=>{const r=record(t.n);return `<button class="task-item ${activeTask===t.n?'active':''}" data-n="${t.n}"><span class="task-no">${String(t.n).padStart(2,'0')}</span><span class="task-name">${t.t}<span class="task-meta">${t.g}</span></span><i class="status-dot ${r.correct?'correct':r.confidence==='review'?'review':''}"></i></button>`}).join('')||'<p class="empty-state">По такому запросу пока ничего нет.</p>';list.querySelectorAll('.task-item').forEach(b=>b.onclick=()=>{activeTask=Number(b.dataset.n);renderList();renderTask();document.querySelector('#task-panel').scrollIntoView({behavior:'smooth',block:'nearest'})})}
function renderTask(){const t=tasks.find(x=>x.n===activeTask)||tasks[0];const r=record(t.n);const checked=r.attempts>0;const isCorrect=r.correct;document.querySelector('#task-panel').innerHTML=`<div class="task-topline"><span>ЗАДАНИЕ ${String(t.n).padStart(2,'0')} · 1 БАЛЛ</span><span class="tag">${t.g}</span></div><h3>${t.t}</h3><p class="task-prompt">${t.p}</p><details class="task-hint"><summary>Небольшая подсказка</summary><p>${t.h}</p></details><div class="answer-row"><input id="answer-input" type="text" autocomplete="off" placeholder="Твой ответ" aria-label="Ответ"><button id="check-answer" class="button primary">Проверить</button></div><div id="feedback" class="feedback ${checked?(isCorrect?'ok':'no'):''}" aria-live="polite">${checked?(isCorrect?'Верно! Хорошая работа.':'Пока не совпало. Посмотри решение и попробуй объяснить шаг.') : ''}</div>${checked||teacherMode?`<div class="solution"><strong>Разбор</strong><br>${t.s}</div>`:''}<details class="python-block"><summary>Как решить это кодом</summary><pre>${escapeHtml(t.c)}</pre></details><div class="reflection"><span>Как получилось решить?</span><button class="confidence ${r.confidence==='independent'?'selected':''}" data-value="independent">Самостоятельно</button><button class="confidence ${r.confidence==='help'?'selected':''}" data-value="help">С подсказкой</button><button class="confidence ${r.confidence==='review'?'selected':''}" data-value="review">Нужно повторить</button></div><div class="teacher-only teacher-check"><label><input type="checkbox" id="verified" ${r.verified?'checked':''}> Ученица объяснила решение своими словами</label><textarea class="note-input" id="task-note" rows="2" placeholder="Заметка по этому номеру">${escapeHtml(r.note||'')}</textarea></div>`;
document.querySelector('#check-answer').onclick=()=>{const value=document.querySelector('#answer-input').value;const ok=normalize(value)===normalize(t.a);r.attempts++;r.correct=ok;save();renderTask()};document.querySelector('#answer-input').onkeydown=e=>{if(e.key==='Enter')document.querySelector('#check-answer').click()};document.querySelectorAll('.confidence').forEach(b=>b.onclick=()=>{r.confidence=b.dataset.value;save();renderTask()});if(document.querySelector('#verified'))document.querySelector('#verified').onchange=e=>{r.verified=e.target.checked;save()};if(document.querySelector('#task-note'))document.querySelector('#task-note').oninput=e=>{r.note=e.target.value;save()}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderProgress(){const groups=[...new Set(tasks.map(t=>t.g))];document.querySelector('#topic-progress').innerHTML=groups.map(g=>{const set=tasks.filter(t=>t.g===g),done=set.filter(t=>record(t.n).confidence==='independent'||record(t.n).verified).length;return `<div class="topic-row"><span>${g}</span><div class="topic-meter"><i style="width:${done/set.length*100}%"></i></div><small>${done}/${set.length}</small></div>`}).join('');const todo=tasks.filter(t=>record(t.n).confidence==='review'||(record(t.n).attempts&&!record(t.n).correct));document.querySelector('#review-list').innerHTML=todo.length?todo.map(t=>`<a class="review-link" href="#practice" data-open="${t.n}"><b>${String(t.n).padStart(2,'0')}</b><span>${t.t}</span></a>`).join(''):'<p class="empty-state">Пока нет отмеченных пробелов. Отметьте «Нужно повторить» после разбора сложного номера.</p>';document.querySelectorAll('[data-open]').forEach(a=>a.onclick=()=>{activeTask=Number(a.dataset.open);showView('practice');renderList();renderTask()});document.querySelector('#lesson-note').value=state.note||''}
function showView(which){document.querySelector('#practice-view').classList.toggle('hidden',which!=='practice');document.querySelector('#progress-view').classList.toggle('hidden',which!=='progress');document.querySelectorAll('.nav-link[data-view]').forEach(a=>a.classList.toggle('active',a.dataset.view===which));if(which==='progress')renderProgress()}
document.querySelectorAll('.nav-link[data-view]').forEach(a=>a.onclick=e=>{e.preventDefault();showView(a.dataset.view)});document.querySelector('#mode-toggle').onclick=()=>{teacherMode=!teacherMode;document.body.classList.toggle('teacher-mode',teacherMode);document.querySelector('#mode-toggle').textContent=teacherMode?'Режим: преподаватель':'Режим: ученица';renderTask()};document.querySelector('#mode-toggle').textContent='Режим: ученица';document.querySelector('#search').oninput=renderList;document.querySelector('#hero-date').textContent=new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date());document.querySelector('#save-note').onclick=()=>{state.note=document.querySelector('#lesson-note').value;localStorage.setItem(key,JSON.stringify(state));document.querySelector('#note-saved').textContent='Сохранено';setTimeout(()=>document.querySelector('#note-saved').textContent='',1800)};document.querySelector('#export-btn').onclick=()=>{const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='progress-ege-informatika.json';a.click();URL.revokeObjectURL(a.href)};document.querySelector('#import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const imported=JSON.parse(await f.text());if(!imported.tasks)throw new Error();state={tasks:imported.tasks,note:imported.note||''};localStorage.setItem(key,JSON.stringify(state));renderStats();renderList();renderTask();renderProgress();alert('Отчёт загружен.')}catch{alert('Не получилось прочитать этот файл прогресса.')}};document.querySelector('#reset-btn').onclick=()=>{if(confirm('Сбросить прогресс и заметки на этом устройстве?')){state={tasks:{},note:''};localStorage.setItem(key,JSON.stringify(state));renderStats();renderList();renderTask();renderProgress()}};
renderFilters();renderStats();renderList();renderTask();

