const topics=["Все темы","Логика и теория","Алгоритмы","Данные и файлы","Графы и сети"];
const tasks=[
  {"n":1,"t":"Графы и матрица смежности","g":"Графы и сети","p":"По схеме графа посчитай число простых маршрутов из A в F. Повторно заходить в одну вершину нельзя.","a":"13","h":"Единица выше диагонали означает одно ребро. Для маршрутов запрещай повтор вершин.","s":"Рёбра: AB, AC, BC, BD, CD, CE, DE, DF, EF. Простых маршрутов A→F — 13.","c":"g={\n 'A':['B','C'], 'B':['A','C','D'],\n 'C':['A','B','D','E'], 'D':['B','C','E','F'],\n 'E':['C','D','F'], 'F':['D','E']}\ndef dfs(v,seen):\n if v=='F': return 1\n return sum(dfs(w,seen|{w}) for w in g[v] if w not in seen)\nprint(dfs('A',{'A'}))  # 13 маршрутов","img":"assets/viz01.png"},
  {"n":2,"t":"Логическое выражение","g":"Логика и теория","p":"Для F=(x ИЛИ y) И НЕ z выпиши число наборов, на которых F=1. Затем отдельно проверь набор (1,0,0).","a":"3","h":"Сначала столбцы в скобках и НЕ, затем итоговое И.","s":"F=1 для 010,100,110 — всего 3 набора. F(1,0,0)=1.","c":"from itertools import product\nrows=[t for t in product([0,1],repeat=3) if (t[0] or t[1]) and not t[2]]\nprint(rows,len(rows))","img":"assets/viz02.png"},
  {"n":3,"t":"Запрос к базе данных","g":"Данные и файлы","p":"По таблице покупок найди сумму стоимости заказов «Книга» с количеством не менее 2.","a":"2525","h":"Фильтр по обоим условиям, затем цена умножается на количество.","s":"Подходят заказы 101,104,106. Сумма: 350×2 + 275×3 + 500×2 = 2525.","c":"rows=[('Книга',350,2),('Тетрадь',80,4),\n ('Книга',420,1),('Книга',275,3),('Книга',500,2)]\nanswer=sum(p*q for c,p,q in rows if c=='Книга' and q>=2)\nprint(answer)","img":"assets/viz03.png"},
  {"n":4,"t":"Кодирование и дерево Хаффмана","g":"Логика и теория","p":"Для частот A=2,B=3,C=5,D=8,E=13 построй дерево Хаффмана. Найди сумму частота×длина кода по всем буквам.","a":"64","h":"Объединяй два минимума, сумму возвращай в очередь.","s":"Слияния весов: 2+3=5; 5+5=10; 8+10=18; 13+18=31. Взвешенная сумма длин равна сумме весов объединений: 5+10+18+31=64.","c":"import heapq\nh=[2,3,5,8,13]; heapq.heapify(h); cost=0\nwhile len(h)>1:\n a=heapq.heappop(h); b=heapq.heappop(h); cost+=a+b; heapq.heappush(h,a+b)\nprint(cost)  # взвешенная длина дерева","img":"assets/viz04.png"},
  {"n":5,"t":"Преобразование двоичной записи","g":"Алгоритмы","p":"Для N=13 запиши двоичную форму, справа допиши N mod 2, удали первый бит и переведи результат в десятичную систему.","a":"11","h":"Следи за порядком строковых действий.","s":"13=1101; нечётно, дописываем 1: 11011; убираем первый бит: 1011₂=11.","c":"n=13; s=bin(n)[2:]+str(n%2); s=s[1:]\nprint(s,int(s,2))  # 1011, 11","img":"assets/viz05.png"},
  {"n":6,"t":"Исполнитель и координаты","g":"Алгоритмы","p":"Исполнитель начинает в (0,0) и выполняет команды на схеме. Запиши конечные координаты x,y.","a":"2,2","h":"Веди координаты и направление после каждой команды.","s":"Траектория: (0,0)→(3,0)→(3,2)→(2,2). Ответ: 2,2. Замкнутая с осями площадь равна 6.","c":"x,y=0,0; dx,dy=1,0\nx+=3*dx; y+=3*dy\ndx,dy=-dy,dx; x+=2*dx; y+=2*dy\ndx,dy=dy,-dx; x-=dx; y-=dy\nprint(x,y)","img":"assets/viz06.png"},
  {"n":7,"t":"Объём изображения и звука","g":"Логика и теория","p":"Изображение 320×200 пикселей использует палитру 16 цветов. Найди объём в Кбайтах без заголовка. Введи число с десятичной запятой или точкой.","a":["31,25","31.25"],"h":"i=log₂(цветов); битность×число пикселей; переведи бит→байт→Кбайт.","s":"На пиксель нужно 4 бита. 320×200×4=256000 бит=32000 байт=31,25 Кбайт.","c":"w,h,colors=320,200,16\ni=(colors-1).bit_length()\nprint(w*h*i/8/1024,'Кбайт')","img":"assets/viz07.png"},
  {"n":8,"t":"Комбинаторика","g":"Логика и теория","p":"Сколько паролей можно составить из трёх разных цифр, если первая цифра не равна нулю?","a":"648","h":"Запрет нуля касается только первого места; повторы запрещены.","s":"9×9×8=648.","c":"print(9*9*8)  # первая цифра не 0; повторы запрещены","img":"assets/viz08.png"},
  {"n":9,"t":"Электронная таблица","g":"Данные и файлы","p":"Сколько учеников одновременно набрали математику не ниже 70 и информатику не ниже 75?","a":"4","h":"Порог должен выполняться одновременно.","s":"Проходят Аня, Глеб, Даша и Егор — 4 ученика. Среднее по информатике среди них: (91+75+79+84)/4=82,25.","c":"rows=[('Аня',82,91),('Борис',68,88),('Вера',74,72),\n ('Глеб',70,75),('Даша',95,79),('Егор',71,84)]\na=[r[2] for r in rows if r[1]>=70 and r[2]>=75]\nprint(len(a),sum(a)/len(a))","img":"assets/viz09.png"},
  {"n":10,"t":"Маска сети IPv4","g":"Графы и сети","p":"IP 192.168.12.34 и маска 255.255.255.192. Запиши наибольший допустимый адрес узла.","a":"192.168.12.62","h":"Размер блока: 256−192. Найди диапазон, куда попало 34.","s":"Маска /26 задаёт блоки по 64 адреса. 34 находится в диапазоне .0–.63; адрес сети .0, broadcast .63, последний адрес узла .62.","c":"ip=34; block=256-192; net=ip//block*block\nprint(net,net+block-2)  # последний обычный адрес узла","img":"assets/viz10.png"},
  {"n":11,"t":"Объём текстового файла","g":"Логика и теория","p":"Текст содержит 120 символов по 16 бит на символ. Найди объём файла в байтах.","a":"240","h":"Сначала умножение, затем деление на 8.","s":"120×16=1920 бит; 1920/8=240 байт. После удаления пробелов для 100 символов объём был бы 200 байт.","c":"print(120*16,'бит',120*16//8,'байт')\nprint(100*16//8,'байт')","img":"assets/viz11.png"},
  {"n":12,"t":"Редактор строк","g":"Алгоритмы","p":"Редактор заменяет первое AB на BBA до остановки. Введи итоговую строку для ABBA.","a":"BBBBAA","h":"После каждой замены ищи первое AB заново.","s":"ABBA→BBABA→BBBBAA. Две замены; в результате AB отсутствует.","c":"s='ABBA'; steps=0\nwhile 'AB' in s:\n s=s.replace('AB','BBA',1); steps+=1\nprint(s,steps)","img":"assets/viz12.png"},
  {"n":13,"t":"Перебор чисел программой","g":"Алгоритмы","p":"Среди двузначных чисел найди сумму чисел, кратных 7 и не кратных 5.","a":"623","h":"Перечисли кратные 7 и исключи кратные 5.","s":"Кратные 7 от 10 до 99: 14,…,98. Исключаем 35 и 70. Всего 11 чисел; их сумма 728−105=623.","c":"a=[n for n in range(10,100) if n%7==0 and n%5!=0]\nprint(len(a),sum(a))","img":"assets/viz13.png"},
  {"n":14,"t":"Системы счисления","g":"Логика и теория","p":"Переведи 173₁₀ в восьмеричную систему. Введи цифры ответа без индекса основания.","a":"255","h":"Остатки читаются снизу вверх.","s":"Ответ 255₈; проверка 2×64+5×8+5=173.","c":"n=173; out=[]\nwhile n: n,r=divmod(n,8); out.append(str(r))\nprint(''.join(out[::-1]))","img":"assets/viz14.png"},
  {"n":15,"t":"Логика с параметром","g":"Логика и теория","p":"Найди наибольшее целое A, при котором для всех целых x верно (x≤A) → (x<5).","a":"4","h":"Ищи контрпример на границе.","s":"Ответ A=4. При A=5 x=5 даёт ложь; при A≤4 условие x≤A влечёт x<5.","c":"# Если A>=5, контрпример x=5 делает импликацию ложной.\n# При A<=4 все x<=A удовлетворяют x<5; максимум A=4.","img":"assets/viz15.png"},
  {"n":16,"t":"Рекуррентная последовательность","g":"Алгоритмы","p":"Дано A₁=2, Aₙ₊₁=3Aₙ−1. Найди A₄.","a":"41","h":"Каждый раз подставь предыдущий член.","s":"A₂=5,A₃=14,A₄=41.","c":"a=2\nfor _ in range(3): a=3*a-1\nprint(a)","img":"assets/viz16.png"},
  {"n":17,"t":"Файл и соседние пары","g":"Данные и файлы","p":"В ряду 6,10,15,7,9,20,30 посчитай соседние пары, где одно число делится на 3, другое на 5.","a":"4","h":"Проверяй len−1 соседних пар; порядок делителей не важен.","s":"Подходят (6,10),(10,15),(9,20),(20,30). Ответ: 4 пары.","c":"a=[6,10,15,7,9,20,30]; count=0\nfor x,y in zip(a,a[1:]):\n if (x%3==0 and y%5==0) or (x%5==0 and y%3==0): count+=1\nprint(count)","img":"assets/viz17.png"},
  {"n":18,"t":"Динамическое программирование","g":"Алгоритмы","p":"Робот идёт вправо или вниз по таблице стоимостей. Найди минимальную стоимость пути с включёнными стартом и финишем.","a":"12","h":"Клетка = её цена + минимум сверху и слева.","s":"Таблица минимумов по строкам: 1 5 7 15 / 4 6 11 12 / 13 7 9 12 / 17 10 10 12. Ответ 12.","c":"c=[[1,4,2,8],[3,2,5,1],[9,1,2,3],[4,3,1,2]]\nd=[[0]*4 for _ in c]\nfor i in range(4):\n for j in range(4):\n  up=d[i-1][j] if i else 10**9\n  left=d[i][j-1] if j else 10**9\n  d[i][j]=c[i][j]+min(up,left)\nprint(d[-1][-1])","img":"assets/viz18.png"},
  {"n":19,"t":"Игра: позиция и выигрышный ход","g":"Логика и теория","p":"В куче 10 камней; можно добавить 1 или 2; цель — не менее 13. Выигрывает ли первый при оптимальной игре? Ответь да или нет.","a":"нет","h":"Если оба хода начинающего оставляют сопернику немедленный выигрыш, стартовая позиция проигрышная.","s":"Из 10 можно получить 11 или 12. Из 11 соперник добавит 2 и достигнет 13; из 12 добавит 1. Начинающий не гарантирует победу.","c":"# Из 10 оба перехода (11,12) оставляют сопернику немедленный ход в 13.\n# Значит, у начинающего нет гарантии выиграть.","img":"assets/viz19.png"},
  {"n":20,"t":"Игра: выигрыш своим вторым ходом","g":"Логика и теория","p":"В куче 5 камней; ходы +1/+2; цель 9. Первый начинает с +1. Сколько камней будет, когда он гарантированно выиграет своим вторым ходом?","a":"9","h":"Перечисли все ответы соперника и покажи выигрышный ответ в каждом случае.","s":"Первый получает 6. Ответ соперника — 7 или 8. Из 7 первый добавляет 2 до 9, из 8 добавляет 1 до 9. Ответ: 9 камней.","c":"# Первый: 5→6. Если соперник делает 6→7, первый +2 до 9.\n# Если 6→8, первый +1 до 9.","img":"assets/viz20.png"},
  {"n":21,"t":"Игра с умножением и сложением","g":"Логика и теория","p":"Куча 8; ходы ×2 или +3; цель не менее 20. Может ли первый гарантировать победу при оптимальной игре? Ответь да или нет.","a":"нет","h":"Проверь, есть ли для первого ход, после которого оба ответа соперника проигрышны.","s":"Из 8 первый получает 16 или 11. Соперник в обоих случаях может умножить на 2 и сразу получить не менее 20. Ответ: нет.","c":"# Из 8 первый получает 16 или 11. Соперник в обоих случаях\n# умножает на 2 и сразу достигает цели 20 или больше.","img":"assets/viz21.png"},
  {"n":22,"t":"Параллельные процессы","g":"Алгоритмы","p":"A длится 4 минуты. B длится 3 и начинается после A. C длится 6 параллельно с A. D длится 2 и ждёт B и C. Найди полное время.","a":"9","h":"Поздний предшественник определяет старт следующего.","s":"B закончится в 7, C в 6; D стартует в max(7,6)=7 и закончится в 9 минут.","c":"finish={'A':4,'B':7,'C':6}; finish['D']=max(finish['B'],finish['C'])+2\nprint(finish['D'])","img":"assets/viz22.png"},
  {"n":23,"t":"Взвешенные маршруты","g":"Графы и сети","p":"По взвешенному графу найди длину кратчайшего пути S→T.","a":"8","h":"Сложи вес каждого полного пути.","s":"Маршруты имеют длины 9,13,10,8. Кратчайший S→B→D→T; длина 8.","c":"import heapq\ng={\n 'S':[('A',4),('B',2)], 'A':[('C',3),('D',5)],\n 'B':[('C',6),('D',2)], 'C':[('T',2)],\n 'D':[('T',4)], 'T':[]}\nd={'S':0}; q=[(0,'S')]\nwhile q:\n x,v=heapq.heappop(q)\n if x!=d[v]: continue\n for w,c in g[v]:\n  if x+c<d.get(w,10**9):\n   d[w]=x+c; heapq.heappush(q,(d[w],w))\nprint(d['T'])","img":"assets/viz23.png"},
  {"n":24,"t":"Поиск серий в строке","g":"Алгоритмы","p":"В строке ABCCCAAABB найди длину самой длинной серии одинаковых символов.","a":"3","h":"Текущая длина сбрасывается при смене символа; максимум обновляй каждый шаг.","s":"Длины 1,1,3,3,2; ответ 3.","c":"s='ABCCCAAABB'; best=cur=1\nfor i in range(1,len(s)):\n cur=cur+1 if s[i]==s[i-1] else 1; best=max(best,cur)\nprint(best)","img":"assets/viz24.png"},
  {"n":25,"t":"Делители числа","g":"Алгоритмы","p":"Найди количество положительных делителей числа 360.","a":"24","h":"Каждый малый делитель даёт пару; √N добавляй однократно, если квадрат.","s":"Пары делителей до √360: 12 различных пар, квадратный корень не является делителем. Всего 24 делителя.","c":"from math import isqrt\nn=360; ds=set()\nfor d in range(1,isqrt(n)+1):\n if n%d==0: ds.update((d,n//d))\nprint(sorted(ds),len(ds))","img":"assets/viz25.png"},
  {"n":26,"t":"Жадный выбор интервалов","g":"Данные и файлы","p":"Для интервалов (1,4),(3,5),(4,7),(6,8),(8,10) найди максимум непересекающихся заявок. Соседство границ разрешено.","a":"3","h":"Сортируй по окончанию; бери, если старт ≥ конец предыдущего.","s":"Жадно выбираем по самому раннему завершению: (1,4),(4,7),(8,10). Максимум — 3 заявки.","c":"jobs=[(1,4),(3,5),(4,7),(6,8),(8,10)]; chosen=[]; end=-1\nfor a,b in sorted(jobs,key=lambda t:t[1]):\n if a>=end: chosen.append((a,b)); end=b\nprint(chosen)","img":"assets/viz26.png"},
  {"n":27,"t":"Кластеризация точек","g":"Данные и файлы","p":"Точки на рисунке образуют группы по близости. Сколько кластеров получится? Назови критерий группировки.","a":"3","h":"Сначала кластеризуй по близости, потом усредни x и y внутри каждой группы.","s":"Группы {A,B},{C,D},{E}; центры (1.5,1),(8.5,8),(20,2). Между первыми √98≈9.90; между вторым и третьим √168.25≈12.97. Критерий группировки должен быть назван.","c":"groups=[[(1,1),(2,1)],[(8,8),(9,8)],[(20,2)]]\ncenters=[]\nfor group in groups:\n cx=sum(x for x,y in group)/len(group)\n cy=sum(y for x,y in group)/len(group)\n centers.append((cx,cy))\nprint(centers)","img":"assets/viz27.png"}
];

// По две новые проверочные задачи по каждой теме. Они вставляются в экзамен сразу после ошибки.
const remedialBank={
1:[['Дороги A–B=1, B–D=2, A–D=5. Найди кратчайший путь A→D.','3','A–B–D: 1+2=3, это короче прямой дороги.'],['A–B=3, B–D=4, A–C=2, C–D=8, A–D=9. Какова длина кратчайшего пути A→D?','7','A–B–D имеет длину 7.']],
2:[['Для скольких наборов (x,y,z) ровно одна переменная равна 1?','3','Подходят 100, 010 и 001.'],['Сколько наборов двух переменных дают истину выражению x И y?','1','Только набор 11.']],
3:[['Баллы: 4, 7, 9, 5, 8. Сколько значений не меньше 7?','3','Подходят 7, 9 и 8.'],['Количество заказов: 2, 6, 6, 3, 9. Сколько заказов содержат не менее 6 товаров?','3','Подходят три значения: 6, 6, 9.']],
4:[['Кодовые слова 0, 10, 110. Какое кратчайшее слово длины 3 можно добавить без нарушения Фано?','111','0,10 и 110 уже заняли другие ветви; 111 свободно.'],['Кодовые слова 0,10,110,1110. Какое слово длины 4 можно добавить?','1111','1111 не является началом другого слова и не начинается с существующего.']],
5:[['Начни с 2 и дважды выполни n=2n+1. Ответ?','11','2→5→11.'],['Начни с 4 и трижды выполни n=2n+1. Ответ?','39','4→9→19→39.']],
6:[['Старт (0,0): вправо 5, вверх 2, влево 3. Запиши x,y.','2,2','x=5−3=2, y=2.'],['Старт (0,0): вверх 4, вправо 2, вниз 1. Запиши x,y.','2,3','x=2, y=4−1=3.']],
7:[['Изображение 100×50, палитра 8 цветов. Сколько бит без сжатия?','15000','На пиксель 3 бита; 100×50×3=15000.'],['Изображение 64×32, палитра 2 цвета. Сколько бит без сжатия?','2048','Один бит на пиксель: 64×32=2048.']],
8:[['Сколькими способами можно расставить 4 разные книги?','24','4!=24.'],['Сколькими способами можно расставить 6 разных книг?','720','6!=720.']],
9:[['Значения 4, 10, 12, 15, 18. Сколько чисел попадает в диапазон [10;15]?','3','Подходят 10,12,15; обе границы включены.'],['Баллы 7,8,11,14,20. Сколько значений в диапазоне [8;14]?','3','Подходят 8,11,14.']],
10:[['IP 192.168.1.70, маска 255.255.255.224. Найди сумму октетов адреса сети.','425','Размер блока 32; 70 лежит в блоке 64–95. Сеть .64; сумма 192+168+1+64=425.'],['IP 10.0.5.200, маска 255.255.255.128. Найди сумму октетов адреса сети.','143','Блок 128; сеть 10.0.5.128; сумма 143.']],
11:[['Сообщение из 20 символов алфавита из 8 знаков. Сколько бит?','60','На символ log₂8=3 бита; 20×3=60.'],['Сообщение из 16 символов алфавита из 16 знаков. Сколько бит?','64','На символ 4 бита; 16×4=64.']],
12:[['Самое левое «11» заменяют на «2» до остановки. Сколько замен в строке 11111111?','4','Каждая замена убирает две единицы; четыре раза.'],['То же правило для строки 11111. Сколько замен?','2','11111→2111→221.']],
13:[['Команды +1 и +2. Сколько программ ведут из 1 в 6?','8','Число способов для разницы 5 — 8 (рекурсия Фибоначчи).'],['Команды +1 и +2. Сколько программ ведут из 1 в 7?','13','Для разницы 6 получаем 13 программ.']],
14:[['Переведи 11001₂ в десятичную систему.','25','16+8+1=25.'],['Переведи 11100₂ в десятичную систему.','28','16+8+4=28.']],
15:[['Сколько x от 0 до 10 включительно удовлетворяет x<4 ИЛИ x>8?','6','Подходят 0,1,2,3,9,10.'],['Сколько x от 0 до 10 удовлетворяет x<2 ИЛИ x>8?','4','Подходят 0,1,9,10.']],
16:[['G₀=2,G₁=1,Gₙ=Gₙ₋₁+2Gₙ₋₂. Найди G₄.','17','G₂=5,G₃=7,G₄=17.'],['H₀=1,H₁=3,Hₙ=2Hₙ₋₁+Hₙ₋₂. Найди H₄.','41','H₂=7,H₃=17,H₄=41.']],
17:[['Ряд 2,4,5,7,8. Сколько соседних пар имеют сумму, кратную 3?','2','Пары (4,5) дают 9; (7,8) дают 15.'],['Ряд 3,6,1,2,4. Сколько соседних пар имеют сумму, кратную 2?','1','Только пара (2,4) даёт чётную сумму; ответ 1.']],
18:[['Сетка 2×2: 2 7 / 4 3. Робот вправо/вниз. Найди максимальную сумму пути.','12','Вправо-вниз: 2+7+3=12; вниз-вправо: 2+4+3=9.'],['Сетка 2×2: 5 1 / 2 6. Найди максимальную сумму пути.','13','Вниз-вправо: 5+2+6=13; вправо-вниз: 12.']],
19:[['Куча 8, ход +2 или +4, цель не менее 12. Может ли первый выиграть первым ходом? Ответ да/нет.','да','Ход +4 сразу даёт 12.'],['Куча 10, ход +1 или +2, цель 15. Выигрывает ли первый за один ход? Ответ да/нет.','нет','Максимум после одного хода — 12.']],
20:[['В куче 7; ход +1 или +3; цель 10. Какой немедленный выигрышный ход? Запиши число.','3','7+3=10.'],['В куче 12; ход +2 или +5; цель 17. Какой ход выигрывает?','5','12+5=17.']],
21:[['Куча 4, ходы +1/+2, цель 9. Первый ход +2 оставляет 6. После ответа соперника 7 или 8; какой ход первого выигрывает в обоих случаях?','2','Из 7 добавить 2; из 8 тоже можно добавить 2, получим не меньше 9.'],['Куча 6, ходы +1/+2, цель 11. Первый добавляет 2, оставляя 8. После ответа соперника 9 или 10 какой ход выигрывает?','2','Из 9 добавить 2 до 11; из 10 достаточно добавить 1.']],
22:[['A и B параллельны, длятся 2 и 7 минут. C длится 3 минуты после обеих. Общее время?','10','C стартует на 7-й минуте и заканчивается на 10-й.'],['Две параллельные работы длятся 4 и 6 минут; затем работа 5 минут. Общее время?','11','6+5=11.']],
23:[['Пути A→B=2, B→D=5, A→C=4, C→D=1. Кратчайшая длина A→D?','5','Через C: 4+1=5; через B: 7.'],['A→B=3, B→D=2, A→C=1, C→D=8. Найди кратчайшую длину.','5','Через B: 3+2=5.']],
24:[['Найди максимальную серию A в строке AAABAA.','3','Самая длинная серия — первые три A.'],['Найди максимальную серию B в строке ABBBAABBBB.','4','Последняя серия B имеет длину 4.']],
25:[['Сколько положительных делителей у 48?','10','48=2⁴×3; число делителей (4+1)(1+1)=10.'],['Сколько положительных делителей у 36?','9','Делители: 1,2,3,4,6,9,12,18,36.']],
26:[['Интервалы [1,2],[2,4],[4,6],[3,5]. Максимум непересекающихся занятий?','3','Берём первые три: [1,2],[2,4],[4,6].'],['Интервалы [0,3],[1,2],[2,4],[4,5]. Максимум непересекающихся?','3','Можно взять [1,2],[2,4],[4,5].']],
27:[['Две группы точек: в первой 3 точки, во второй 5. Каков размер наибольшего кластера?','5','Сравни размеры кластеров: максимум 5.'],['Три группы содержат 2,4 и 3 точки. Размер крупнейшего кластера?','4','Наибольшая группа содержит 4 точки.']]
};

const key='egeProgress2027-v1';
let state=loadState(); let activeFilter='Все темы'; let activeTask=1; let teacherMode=false;let examSession=state.exam||null;
function loadState(){try{return JSON.parse(localStorage.getItem(key))||{tasks:{},note:''}}catch{return {tasks:{},note:''}}}
function save(){state.exam=examSession;localStorage.setItem(key,JSON.stringify(state));renderStats();renderList();if(document.querySelector('#progress-view').classList.contains('hidden')===false)renderProgress()}
function normalize(s){return String(s??'').trim().toLowerCase().replace(/[₀₁₂₃₄₅₆₇₈₉]/g,'').replace(/\s+/g,'').replace(/^\+/,'').replace(/ё/g,'е')}
function record(n){return state.tasks[n]||(state.tasks[n]={attempts:0,correct:false,confidence:'',verified:false,note:''})}
function renderStats(){const vals=Object.values(state.tasks);const viewed=vals.filter(v=>v.attempts||v.confidence||v.verified).length;const correct=vals.filter(v=>v.correct).length;const independent=vals.filter(v=>v.confidence==='independent').length;const review=vals.filter(v=>v.confidence==='review').length;document.querySelector('#stat-viewed').innerHTML=`${viewed} <small>/ 27</small>`;document.querySelector('#stat-correct').textContent=correct;document.querySelector('#stat-independent').textContent=independent;document.querySelector('#stat-review').textContent=review;document.querySelector('#hero-done').textContent=viewed;document.querySelector('#hero-independent').textContent=`${independent} уверенно`;document.querySelector('#hero-needs').textContent=`${review} повторить`;document.querySelector('#hero-bar').style.width=`${viewed/27*100}%`}
function renderFilters(){document.querySelector('#filters').innerHTML=topics.map(t=>`<button class="filter ${t===activeFilter?'active':''}" data-filter="${t}">${t}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;renderFilters();renderList()})}
function visibleTasks(){const q=document.querySelector('#search').value.trim().toLowerCase();return tasks.filter(t=>(activeFilter==='Все темы'||t.g===activeFilter)&&(!q||`${t.n} ${t.t} ${t.g}`.toLowerCase().includes(q)))}
function renderList(){const list=document.querySelector('#task-list');list.innerHTML=visibleTasks().map(t=>{const r=record(t.n);return `<button class="task-item ${activeTask===t.n?'active':''}" data-n="${t.n}"><span class="task-no">${String(t.n).padStart(2,'0')}</span><span class="task-name">${t.t}<span class="task-meta">${t.g}</span></span><i class="status-dot ${r.correct?'correct':r.confidence==='review'?'review':''}"></i></button>`}).join('')||'<p class="empty-state">По такому запросу пока ничего нет.</p>';list.querySelectorAll('.task-item').forEach(b=>b.onclick=()=>{activeTask=Number(b.dataset.n);renderList();renderTask();document.querySelector('#task-panel').scrollIntoView({behavior:'smooth',block:'nearest'})})}
function renderTask(){const t=tasks.find(x=>x.n===activeTask)||tasks[0];const r=record(t.n);const checked=r.attempts>0;const isCorrect=r.correct;document.querySelector('#task-panel').innerHTML=`<div class="task-topline"><span>ЗАДАНИЕ ${String(t.n).padStart(2,'0')} · 1 БАЛЛ</span><span class="tag">${escapeHtml(t.g)}</span></div><h3>${escapeHtml(t.t)}</h3>${t.img?`<img class="task-figure" src="${escapeHtml(t.img)}" alt="Схема к заданию ${t.n}">`:''}<p class="task-prompt">${escapeHtml(t.p)}</p><details class="task-hint"><summary>Небольшая подсказка</summary><p>${escapeHtml(t.h)}</p></details><div class="answer-row"><input id="answer-input" type="text" autocomplete="off" placeholder="Твой ответ" aria-label="Ответ"><button id="check-answer" class="button primary">Проверить</button></div><div id="feedback" class="feedback ${checked?(isCorrect?'ok':'no'):''}" aria-live="polite">${checked?(isCorrect?'Верно! Хорошая работа.':'Пока не совпало. Посмотри решение и попробуй объяснить шаг.') : ''}</div>${checked||teacherMode?`<div class="solution"><strong>Разбор</strong><br>${escapeHtml(t.s)}</div>`:''}<details class="python-block"><summary>Как решить это кодом</summary><pre>${escapeHtml(t.c)}</pre></details><div class="reflection"><span>Как получилось решить?</span><button class="confidence ${r.confidence==='independent'?'selected':''}" data-value="independent">Самостоятельно</button><button class="confidence ${r.confidence==='help'?'selected':''}" data-value="help">С подсказкой</button><button class="confidence ${r.confidence==='review'?'selected':''}" data-value="review">Нужно повторить</button></div><div class="teacher-only teacher-check"><label><input type="checkbox" id="verified" ${r.verified?'checked':''}> Ученица объяснила решение своими словами</label><textarea class="note-input" id="task-note" rows="2" placeholder="Заметка по этому номеру">${escapeHtml(r.note||'')}</textarea></div>`;
document.querySelector('#check-answer').onclick=()=>{const value=document.querySelector('#answer-input').value;const ok=answerMatches(value,t.a);r.attempts++;r.correct=ok;save();renderTask()};document.querySelector('#answer-input').onkeydown=e=>{if(e.key==='Enter')document.querySelector('#check-answer').click()};document.querySelectorAll('.confidence').forEach(b=>b.onclick=()=>{r.confidence=b.dataset.value;save();renderTask()});if(document.querySelector('#verified'))document.querySelector('#verified').onchange=e=>{r.verified=e.target.checked;save()};if(document.querySelector('#task-note'))document.querySelector('#task-note').oninput=e=>{r.note=e.target.value;save()}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function examQuestion(t,remedial=false){return {base:t.n,title:t.t,group:t.g,prompt:t.p,answer:t.a,solution:t.s,img:t.img,remedial,submitted:false,ok:null}}
function makeRemedials(t){return remedialBank[t.base].map(([p,a,s])=>({base:t.base,title:t.title,group:t.group,prompt:p,answer:a,solution:s,img:t.img,remedial:true,submitted:false,ok:null}))}
function beginExam(){examSession={queue:tasks.map(t=>examQuestion(t)),index:0,first:{},right:0,wrong:0,wrongTotal:0,added:0,wrongTopics:{},complete:false};document.querySelector('#exam-intro').classList.add('hidden');document.querySelector('#exam-result').classList.add('hidden');document.querySelector('#exam-active').classList.remove('hidden');save();renderExam()}
function renderExam(){
 const intro=document.querySelector('#exam-intro'),active=document.querySelector('#exam-active'),result=document.querySelector('#exam-result');
 if(!examSession){intro.classList.remove('hidden');active.classList.add('hidden');result.classList.add('hidden');document.querySelector('#start-exam').classList.remove('hidden');document.querySelector('#resume-exam').classList.add('hidden');return}
 if(examSession.complete||examSession.index>=examSession.queue.length){examSession.complete=true;intro.classList.remove('hidden');active.classList.add('hidden');result.classList.remove('hidden');document.querySelector('#start-exam').classList.remove('hidden');document.querySelector('#resume-exam').classList.add('hidden');renderExamResult();return}
 intro.classList.remove('hidden');document.querySelector('#start-exam').classList.toggle('hidden',true);document.querySelector('#resume-exam').classList.remove('hidden');active.classList.remove('hidden');result.classList.add('hidden');
 const q=examSession.queue[examSession.index],answered=examSession.index+1,total=examSession.queue.length;
 document.querySelector('#exam-counter').textContent=`Задание ${answered} из ${total}${q.remedial?' · дополнительное по теме':''}`;
 document.querySelector('#exam-score').textContent=`Верно с первого раза: ${examSession.right}/27 · Ошибок: ${examSession.wrongTotal}`;
 document.querySelector('#exam-bar').style.width=`${Math.min(100,examSession.index/total*100)}%`;
 document.querySelector('#exam-panel').innerHTML=`<div class="exam-question-label">${q.remedial?'ДОПОЛНИТЕЛЬНАЯ ЗАДАЧА':'ЭКЗАМЕН · №'+String(q.base).padStart(2,'0')} · ${escapeHtml(q.group)}</div><h3>${escapeHtml(q.title)}</h3>${q.img?`<img class="task-figure" src="${escapeHtml(q.img)}" alt="Схема к заданию ${q.base}">`:''}<p class="task-prompt">${escapeHtml(q.prompt)}</p>${q.submitted?`<div class="exam-feedback ${q.ok?'ok':'no'}" aria-live="polite">${q.ok?'Ответ принят.':'Ответ не совпал.'}${!q.ok?` Добавлены две задачи по теме «${escapeHtml(q.group)}»; они будут после этого вопроса.`:''}</div>`:`<div class="answer-row"><input id="exam-answer" type="text" autocomplete="off" placeholder="Впиши ответ" aria-label="Ответ на экзаменационное задание"><button id="exam-submit" class="button primary">Ответить</button></div><p class="exam-tip">Подсказки и разбор откроются после завершения экзамена.</p>`}<div class="exam-actions">${q.submitted?'<button id="exam-next" class="button primary">Следующее задание</button>':''}</div>`;
 if(!q.submitted){const submit=()=>submitExamAnswer();document.querySelector('#exam-submit').onclick=submit;document.querySelector('#exam-answer').onkeydown=e=>{if(e.key==='Enter')submit()};document.querySelector('#exam-answer').focus()}else document.querySelector('#exam-next').onclick=nextExamQuestion;
}
function answerMatches(value,answer){return (Array.isArray(answer)?answer:[answer]).some(a=>normalize(value)===normalize(a))}
function submitExamAnswer(){const q=examSession.queue[examSession.index];if(!q||q.submitted)return;const value=document.querySelector('#exam-answer').value.trim();if(!value){document.querySelector('#exam-answer').focus();return}q.submitted=true;q.ok=answerMatches(value,q.answer);if(!q.remedial&&!Object.hasOwn(examSession.first,q.base)){examSession.first[q.base]=q.ok;if(q.ok)examSession.right++;else{examSession.wrong++;examSession.wrongTopics[q.group]=(examSession.wrongTopics[q.group]||0)+1}}if(!q.ok){examSession.wrongTotal++;const extras=makeRemedials(q);examSession.queue.splice(examSession.index+1,0,...extras);examSession.added+=extras.length}save();renderExam()}
function nextExamQuestion(){examSession.index++;if(examSession.index>=examSession.queue.length)examSession.complete=true;save();renderExam()}
function renderExamResult(){const wrong=Object.entries(examSession.wrongTopics);const topicsList=wrong.length?wrong.map(([g,n])=>`<li>${escapeHtml(g)} — ${n} ошибок в основных заданиях</li>`).join(''):'<li>Ошибок в основных заданиях нет.</li>';document.querySelector('#exam-result').innerHTML=`<p class="eyebrow">РЕЗУЛЬТАТЫ</p><h3>Экзамен завершён</h3><div class="exam-result-score">${examSession.right} / 27</div><p>Верно с первой попытки по основным заданиям. Всего ошибок с учётом дополнительных: ${examSession.wrongTotal}. Добавлено тренировочных задач: ${examSession.added}.</p><h4>Темы для разбора</h4><ul>${topicsList}</ul><p>Ответы и пояснения можно открыть в разделе «Практика», где они доступны после проверки.</p><button id="exam-again" class="button primary">Пройти новый экзамен</button>`;document.querySelector('#exam-again').onclick=beginExam}
function renderProgress(){const groups=[...new Set(tasks.map(t=>t.g))];document.querySelector('#topic-progress').innerHTML=groups.map(g=>{const set=tasks.filter(t=>t.g===g),done=set.filter(t=>record(t.n).confidence==='independent'||record(t.n).verified).length;return `<div class="topic-row"><span>${escapeHtml(g)}</span><div class="topic-meter"><i style="width:${done/set.length*100}%"></i></div><small>${done}/${set.length}</small></div>`}).join('');const todo=tasks.filter(t=>record(t.n).confidence==='review'||(record(t.n).attempts&&!record(t.n).correct));document.querySelector('#review-list').innerHTML=todo.length?todo.map(t=>`<a class="review-link" href="#practice" data-open="${t.n}"><b>${String(t.n).padStart(2,'0')}</b><span>${escapeHtml(t.t)}</span></a>`).join(''):'<p class="empty-state">Пока нет отмеченных пробелов. Отметьте «Нужно повторить» после разбора сложного номера.</p>';document.querySelectorAll('[data-open]').forEach(a=>a.onclick=()=>{activeTask=Number(a.dataset.open);showView('practice');renderList();renderTask()});document.querySelector('#lesson-note').value=state.note||'';const e=examSession;document.querySelector('#exam-progress-summary').innerHTML=e?`<strong>${e.complete?'Завершён':'В процессе'}</strong><p>Правильных с первой попытки: ${e.right}/27 · ошибок: ${e.wrongTotal} · добавлено дополнительных задач: ${e.added}</p>${Object.keys(e.wrongTopics).length?`<p>Повторить: ${Object.entries(e.wrongTopics).map(([g,n])=>`${escapeHtml(g)} (${n})`).join(', ')}</p>`:''}`:'<p class="empty-state">Экзамен пока не проходили.</p>'}
function showView(which){document.querySelector('#practice-view').classList.toggle('hidden',which!=='practice');document.querySelector('#progress-view').classList.toggle('hidden',which!=='progress');document.querySelector('#exam-view').classList.toggle('hidden',which!=='exam');document.querySelectorAll('.nav-link[data-view]').forEach(a=>a.classList.toggle('active',a.dataset.view===which));if(which==='progress')renderProgress();if(which==='exam')renderExam()}
document.querySelectorAll('.nav-link[data-view]').forEach(a=>a.onclick=e=>{e.preventDefault();showView(a.dataset.view)});document.querySelector('#start-exam').onclick=beginExam;document.querySelector('#resume-exam').onclick=renderExam;document.querySelector('#mode-toggle').onclick=()=>{teacherMode=!teacherMode;document.body.classList.toggle('teacher-mode',teacherMode);document.querySelector('#mode-toggle').textContent=teacherMode?'Режим: преподаватель':'Режим: ученица';renderTask()};document.querySelector('#mode-toggle').textContent='Режим: ученица';document.querySelector('#search').oninput=renderList;document.querySelector('#hero-date').textContent=new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date());document.querySelector('#save-note').onclick=()=>{state.note=document.querySelector('#lesson-note').value;localStorage.setItem(key,JSON.stringify(state));document.querySelector('#note-saved').textContent='Сохранено';setTimeout(()=>document.querySelector('#note-saved').textContent='',1800)};document.querySelector('#export-btn').onclick=()=>{const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='progress-ege-informatika.json';a.click();URL.revokeObjectURL(a.href)};document.querySelector('#import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const imported=JSON.parse(await f.text());if(!imported.tasks)throw new Error();state={tasks:imported.tasks,note:imported.note||'',exam:imported.exam||null};examSession=state.exam;localStorage.setItem(key,JSON.stringify(state));renderStats();renderList();renderTask();renderProgress();renderExam();alert('Отчёт загружен.')}catch{alert('Не получилось прочитать этот файл прогресса.')}};document.querySelector('#reset-btn').onclick=()=>{if(confirm('Сбросить прогресс и заметки на этом устройстве?')){state={tasks:{},note:'',exam:null};examSession=null;localStorage.setItem(key,JSON.stringify(state));renderStats();renderList();renderTask();renderProgress();renderExam()}};
if(examSession&&!examSession.complete){document.querySelector('#start-exam').classList.add('hidden');document.querySelector('#resume-exam').classList.remove('hidden')}
renderFilters();renderStats();renderList();renderTask();

