const topics=["Все темы","Логика и теория","Алгоритмы","Данные и файлы","Графы и сети"];
const tasks=[
{n:1,t:"Графы и таблицы дорог",g:"Графы и сети",p:"Даны дороги с длинами: A–B = 2, B–C = 3, C–D = 2, A–C = 10, B–D = 8. Найди кратчайшее расстояние из A в D.",a:"7",h:"Сравни прямые маршруты и маршруты с промежуточными городами. Длина пути — сумма длин его рёбер.",s:"A–B–C–D: 2 + 3 + 2 = 7. Другие маршруты длиннее.",c:"Граф можно хранить как список рёбер или словарь соседей. Для такого маленького графа перебери пути; для больших используй Дейкстру."},
{n:2,t:"Таблицы истинности",g:"Логика и теория",p:"Для скольких наборов (x,y) выражение «истинно ровно одно из двух» истинно? x и y — логические переменные.",a:"2",h:"Запиши четыре пары: 00, 01, 10, 11.",s:"Подходят 01 и 10: ответ 2. Это исключающее ИЛИ (XOR).",c:"Перебери product([0,1], repeat=2), оставь пары, где x != y."},
{n:3,t:"Базы данных и запросы",g:"Данные и файлы",p:"В таблице: Анна — 5 решённых задач, Борис — 8, Вера — 6, Глеб — 8. Сколько учеников решили не меньше 6 задач?",a:"3",h:"«Не меньше 6» означает ≥ 6. Проверь каждую запись один раз.",s:"Борис, Вера и Глеб: всего 3 ученика.",c:"В SQL это SELECT COUNT(*) FROM results WHERE solved >= 6; в Python — sum(x >= 6 for x in values)."},
{n:4,t:"Кодирование и условие Фано",g:"Логика и теория",p:"Есть кодовые слова 0, 10, 110 и 1110. Какое кратчайшее двоичное слово длины не более 4 можно добавить, чтобы сохранилось условие Фано?",a:"1111",h:"Ни одно слово не должно быть началом другого. Сначала проверь короткие слова и все уже занятые префиксы.",s:"0 и 10 заняты как префиксы; ветвь 110 тоже занята. 1110 занято целиком, а 1111 свободно. Ответ 1111.",c:"Проверяй кандидата c против каждого существующего w: не должно быть c.startswith(w) или w.startswith(c)."},
{n:5,t:"Преобразование числа",g:"Алгоритмы",p:"Алгоритм заменяет число n на 2n + 1. Начни с 3 и выполни три шага. Какое число получится?",a:"31",h:"Выпиши значения после каждого шага: n₀=3, n₁=2n₀+1 и так далее.",s:"3 → 7 → 15 → 31.",c:"for _ in range(3): n = 2*n + 1"},
{n:6,t:"Исполнители и координаты",g:"Алгоритмы",p:"Исполнитель стартует в (0, 0). Команды: вправо на 4, вверх на 3, влево на 2. Какова конечная координата? Ответ запиши как x,y.",a:"2,3",h:"Изменяй отдельно x и y. Влево уменьшает x, вверх увеличивает y.",s:"x = 0 + 4 − 2 = 2; y = 0 + 3 = 3.",c:"x, y = 0, 0; x += 4; y += 3; x -= 2"},
{n:7,t:"Объём изображения и звука",g:"Логика и теория",p:"Изображение имеет размер 320 × 200 пикселей и палитру из 16 цветов. Сколько бит нужно для хранения без сжатия?",a:"256000",h:"16 цветов требуют 4 бита на пиксель, потому что 2⁴ = 16.",s:"320 × 200 × 4 = 256 000 бит.",c:"bits = width * height * ceil(log2(colors))"},
{n:8,t:"Комбинаторика",g:"Логика и теория",p:"Сколькими способами можно расставить на полке 5 разных книг?",a:"120",h:"Все книги разные и порядок важен. Переставляются все 5 объектов.",s:"5! = 5×4×3×2×1 = 120.",c:"import math; answer = math.factorial(5)"},
{n:9,t:"Электронные таблицы",g:"Данные и файлы",p:"В столбце записаны значения: 12, 8, 15, 9, 20, 11. Сколько значений лежит в диапазоне от 10 до 15 включительно?",a:"3",h:"Проверь границы: 10 ≤ x ≤ 15. Значения 10 и 15 тоже включаются.",s:"Подходят 12, 15 и 11. Ответ 3.",c:"sum(10 <= x <= 15 for x in values)"},
{n:10,t:"IP-адрес и маска",g:"Графы и сети",p:"IP-адрес 192.168.7.130 задан с маской 255.255.255.192. Найди адрес сети и запиши сумму его октетов.",a:"495",h:"В последнем октете маска 192 делит адреса на блоки по 64: 0–63, 64–127, 128–191, 192–255.",s:"130 находится в диапазоне 128–191, значит адрес сети 192.168.7.128. Сумма: 192+168+7+128 = 495.",c:"import ipaddress; net = ipaddress.ip_network('192.168.7.130/255.255.255.192', strict=False); answer = sum(map(int, str(net.network_address).split('.')))"},
{n:11,t:"Количество информации",g:"Логика и теория",p:"Сообщение состоит из 32 символов алфавита из 32 равновероятных знаков. Сколько бит информации в сообщении?",a:"160",h:"Один символ несёт log₂(32)=5 бит.",s:"32 символа × 5 бит = 160 бит.",c:"bits = length * math.log2(alphabet_size)"},
{n:12,t:"Строковый исполнитель",g:"Алгоритмы",p:"Пока в строке есть «11», исполнитель заменяет самое левое вхождение «11» на «2». Сколько замен будет для строки 111111?",a:"3",h:"После каждого шага заново найди самое левое «11». Не заменяй все пары одновременно.",s:"111111 → 21111 → 2211 → 222. Выполнено 3 замены.",c:"while '11' in s: s = s.replace('11', '2', 1); count += 1"},
{n:13,t:"Подсчёт программ исполнителя",g:"Алгоритмы",p:"Исполнитель из числа n делает одну из команд: +1 или +2. Сколько разных программ переводят 1 в 5? Повторять команды можно.",a:"5",h:"Число программ для n получается сложением числа программ, ведущих в n−1 и n−2.",s:"dp[1]=1, dp[2]=1, dp[3]=2, dp[4]=3, dp[5]=5.",c:"dp = [0]*6; dp[1] = 1\nfor n in range(2, 6): dp[n] = dp[n-1] + (dp[n-2] if n >= 3 else 0)"},
{n:14,t:"Системы счисления",g:"Логика и теория",p:"Переведи двоичное число 101101₂ в десятичную систему.",a:"45",h:"Разложи по степеням двойки, справа налево начиная с 2⁰.",s:"32 + 8 + 4 + 1 = 45.",c:"int('101101', 2)"},
{n:15,t:"Логические выражения с параметром",g:"Логика и теория",p:"Сколько целых x от 0 до 9 включительно удовлетворяют условию x < 3 ИЛИ x > 6?",a:"6",h:"Раздели множество на две непересекающиеся части: меньше 3 и больше 6.",s:"Подходят 0,1,2 и 7,8,9. Всего 6.",c:"sum(x < 3 or x > 6 for x in range(10))"},
{n:16,t:"Рекуррентные выражения",g:"Алгоритмы",p:"Дано F₀=1, F₁=2, Fₙ=2Fₙ₋₁+Fₙ₋₂. Найди F₅.",a:"70",h:"Вычисляй последовательно и записывай оба предыдущих значения.",s:"F₂=5, F₃=12, F₄=29, F₅=70.",c:"f = [1, 2]\nfor n in range(2, 6): f.append(2*f[-1] + f[-2])"},
{n:17,t:"Числовая последовательность из файла",g:"Данные и файлы",p:"Последовательность: 6, 12, 9, 15, 10. Сколько соседних пар имеют сумму, кратную 3?",a:"3",h:"Рассмотри пары (6,12), (12,9), (9,15), (15,10). Соседство важно.",s:"Суммы: 18, 21, 24, 25. Первые три кратны 3, ответ 3.",c:"sum((a+b) % 3 == 0 for a,b in zip(data, data[1:]))"},
{n:18,t:"Динамика по клеткам",g:"Алгоритмы",p:"Робот идёт только вправо или вниз по таблице 2×2: верхний ряд 1, 5; нижний ряд 3, 2. Какова максимальная сумма чисел на пути из левой верхней в правую нижнюю клетку?",a:"8",h:"Есть два пути: через 5 или через 3. Включай и стартовую, и финишную клетки.",s:"Путь вправо-вниз: 1+5+2=8; вниз-вправо: 1+3+2=6. Максимум 8.",c:"dp[i][j] = grid[i][j] + max(dp[i-1][j], dp[i][j-1])"},
{n:19,t:"Игра: выигрыш первым ходом",g:"Логика и теория",p:"В куче 10 камней. За ход можно добавить 1 или 3 камня. Побеждает тот, после чьего хода стало не меньше 13. Может ли первый игрок выиграть первым ходом?",a:"да",h:"Проверь, существует ли одна команда, которая сразу достигает 13 или больше.",s:"Да: первый игрок добавляет 3 и получает 13.",c:"any(s + move >= target for move in moves)"},
{n:20,t:"Игра: найти выигрышный ответ",g:"Логика и теория",p:"После хода соперника в куче 6 камней. Сейчас твой ход; можно добавить 1 или 2. Победа наступает при 8 камнях или больше. Какой ход гарантирует победу прямо сейчас?",a:"+2",h:"Проверь результат каждой разрешённой команды.",s:"Нужно добавить 2: получится 8 и условие победы выполнено.",c:"winning_moves = [m for m in moves if s + m >= target]"},
{n:21,t:"Игра: стратегия на несколько ходов",g:"Логика и теория",p:"В куче 5 камней. Игроки по очереди добавляют 1 или 2. Победа — получить не меньше 10. Какой первый ход гарантирует победу первому игроку на его следующем ходу, даже если соперник отвечает оптимально?",a:"+2",h:"После первого хода оставь сопернику 7. Тогда после его ответа останется 8 или 9, и можно добрать до 10.",s:"Первым ходом +2: станет 7. Соперник сделает 8 или 9. Затем +2 выигрывает в обоих случаях.",c:"Перебери первый ход, затем все ответы соперника (all), затем существующий ответ игрока (any)."},
{n:22,t:"Параллельные процессы",g:"Алгоритмы",p:"Работы A и B идут параллельно и занимают 3 и 5 минут. Работа C длится 4 минуты и начинается только после завершения обеих. За сколько минут закончатся все работы?",a:"9",h:"A и B идут одновременно, значит к C переходят после более долгой работы.",s:"C начнётся через max(3,5)=5 минут. 5+4=9 минут.",c:"finish_C = max(finish_A, finish_B) + duration_C"},
{n:23,t:"Графы: кратчайший путь",g:"Графы и сети",p:"Рёбра ориентированного графа имеют длины: A→B 4, A→C 2, C→B 1, B→D 3, C→D 9. Найди длину кратчайшего пути A→D.",a:"6",h:"Сравни маршруты A→B→D и A→C→B→D, а также A→C→D.",s:"A→C→B→D имеет длину 2+1+3=6, это кратчайший путь.",c:"Дейкстра для весов ≥ 0; для маленького DAG можно перебрать пути или посчитать динамикой."},
{n:24,t:"Обработка строк",g:"Алгоритмы",p:"Найди длину самой длинной подряд идущей серии символов A в строке ABAAABBBA.",a:"3",h:"Считай текущую серию одинаковых символов; сбрасывай счётчик на другом символе.",s:"Самая длинная серия — AAA, её длина 3.",c:"current = best = 0\nfor ch in s:\n    current = current + 1 if ch == 'A' else 0\n    best = max(best, current)"},
{n:25,t:"Делители числа",g:"Алгоритмы",p:"Сколько положительных делителей у числа 36?",a:"9",h:"Делители удобно искать парами до √36=6.",s:"Делители: 1,2,3,4,6,9,12,18,36. Всего 9.",c:"sum(36 % d == 0 for d in range(1, 37))"},
{n:26,t:"Интервалы и жадный выбор",g:"Данные и файлы",p:"Нужно выбрать максимум непересекающихся занятий; завершение ровно в момент начала следующего разрешено. Интервалы: [1,3], [2,4], [3,5], [5,7]. Сколько занятий можно выбрать?",a:"3",h:"Отсортируй по времени завершения и каждый раз выбирай самое раннее совместимое занятие.",s:"Берём [1,3], [3,5], [5,7]. Можно выбрать 3 занятия.",c:"events.sort(key=lambda e: e[1]); выбери интервал, если start >= finish_last"},
{n:27,t:"Кластеры точек",g:"Данные и файлы",p:"Четыре точки образуют две явно разделённые группы: (0,0), (0,2) и (10,10), (10,12). Сколько точек в самом большом кластере?",a:"2",h:"Посчитай элементы в каждой из двух групп.",s:"В каждом кластере по 2 точки. Размер самого большого кластера — 2.",c:"Для файловых кластеров строй граф близости точек, ищи компоненты связности и считай элементы в каждой компоненте."}
];

// По две новые проверочные задачи по каждой теме. Они вставляются в экзамен сразу после ошибки.
const remedialBank={
1:[['Дороги A–B=1, B–D=2, A–D=5. Найди кратчайший путь A→D.','3','A–B–D: 1+2=3, это короче прямой дороги.'],['A–B=3, B–D=4, A–C=2, C–D=8, A–D=9. Какова длина кратчайшего пути A→D?','7','A–B–D имеет длину 7.']],
2:[['Для скольких наборов (x,y,z) ровно одна переменная равна 1?','3','Подходят 100, 010 и 001.'],['Сколько наборов двух переменных дают истину выражению x И y?','1','Только набор 11.']],
3:[['Баллы: 4, 7, 9, 5, 8. Сколько значений не меньше 7?','3','Подходят 7, 9 и 8.'],['Количество заказов: 2, 6, 6, 3, 9. Сколько заказов содержат не менее 6 товаров?','3','Подходят три значения: 6, 6, 9.']],
4:[['Кодовые слова 0, 10, 110. Какое кратчайшее слово длины 3 можно добавить без нарушения Фано?','111','0,10 и 110 уже заняли другие ветви; 111 свободно.'],['Кодовые слова 0,10,110,1110. Какое слово длины 4 можно добавить?','1111','1111 не является началом другого слова и не начинается с существующего.']],
5:[['Начни с 2 и дважды выполни n=2n+1. Ответ?','11','2→5→11.'],['Начни с 4 и трижды выполни n=2n+1. Ответ?','39','4→9→19→39.']],
6:[['Старт (0,0): вправо 5, вверх 2, влево 3. Запиши x,y.','2,2','x=5−3=2, y=2.'],['Старт (0,0): вверх 4, вправо 2, вниз 1. Запиши x,y.','2,3','x=2, y=4−1=3.']],
7:[['Изображение 100×50, палитра 8 цветов. Сколько бит без сжатия?','15000','На пиксель 3 бита; 100×50×3=15000.'],['Изображение 64×32, палитра 2 цвета. Сколько бит без сжатия?','2048','Один бит на пиксель: 64×32=2048.']],
8:[['Сколькими способами можно расставить 4 разные книги?','24','4!=24.'],['Сколькими способами можно расставить 6 разных книг?','720','6!=720.']],
9:[['Значения 4, 10, 12, 15, 18. Сколько чисел попадает в диапазон [10;15]?','3','Подходят 10,12,15; обе границы включены.'],['Баллы 7,8,11,14,20. Сколько значений в диапазоне [8;14]?','3','Подходят 8,11,14.']],
10:[['IP 192.168.1.70, маска 255.255.255.224. Найди сумму октетов адреса сети.','425','Размер блока 32; 70 лежит в блоке 64–95. Сеть .64; сумма 192+168+1+64=425.'],['IP 10.0.5.200, маска 255.255.255.128. Найди сумму октетов адреса сети.','143','Блок 128; сеть 10.0.5.128; сумма 143.']],
11:[['Сообщение из 20 символов алфавита из 8 знаков. Сколько бит?','60','На символ log₂8=3 бита; 20×3=60.'],['Сообщение из 16 символов алфавита из 16 знаков. Сколько бит?','64','На символ 4 бита; 16×4=64.']],
12:[['Самое левое «11» заменяют на «2» до остановки. Сколько замен в строке 11111111?','4','Каждая замена убирает две единицы; четыре раза.'],['То же правило для строки 11111. Сколько замен?','2','11111→2111→221.']],
13:[['Команды +1 и +2. Сколько программ ведут из 1 в 6?','8','Число способов для разницы 5 — 8 (рекурсия Фибоначчи).'],['Команды +1 и +2. Сколько программ ведут из 1 в 7?','13','Для разницы 6 получаем 13 программ.']],
14:[['Переведи 11001₂ в десятичную систему.','25','16+8+1=25.'],['Переведи 11100₂ в десятичную систему.','28','16+8+4=28.']],
15:[['Сколько x от 0 до 10 включительно удовлетворяет x<4 ИЛИ x>8?','6','Подходят 0,1,2,3,9,10.'],['Сколько x от 0 до 10 удовлетворяет x<2 ИЛИ x>8?','4','Подходят 0,1,9,10.']],
16:[['G₀=2,G₁=1,Gₙ=Gₙ₋₁+2Gₙ₋₂. Найди G₄.','17','G₂=5,G₃=7,G₄=17.'],['H₀=1,H₁=3,Hₙ=2Hₙ₋₁+Hₙ₋₂. Найди H₄.','41','H₂=7,H₃=17,H₄=41.']],
17:[['Ряд 2,4,5,7,8. Сколько соседних пар имеют сумму, кратную 3?','2','Пары (4,5) дают 9; (7,8) дают 15.'],['Ряд 3,6,1,2,4. Сколько соседних пар имеют сумму, кратную 2?','1','Только пара (2,4) даёт чётную сумму; ответ 1.']],
18:[['Сетка 2×2: 2 7 / 4 3. Робот вправо/вниз. Найди максимальную сумму пути.','12','Вправо-вниз: 2+7+3=12; вниз-вправо: 2+4+3=9.'],['Сетка 2×2: 5 1 / 2 6. Найди максимальную сумму пути.','13','Вниз-вправо: 5+2+6=13; вправо-вниз: 12.']],
19:[['Куча 8, ход +2 или +4, цель не менее 12. Может ли первый выиграть первым ходом? Ответ да/нет.','да','Ход +4 сразу даёт 12.'],['Куча 10, ход +1 или +2, цель 15. Выигрывает ли первый за один ход? Ответ да/нет.','нет','Максимум после одного хода — 12.']],
20:[['В куче 7; ход +1 или +3; цель 10. Какой немедленный выигрышный ход? Запиши число.','3','7+3=10.'],['В куче 12; ход +2 или +5; цель 17. Какой ход выигрывает?','5','12+5=17.']],
21:[['Куча 4, ходы +1/+2, цель 9. Первый ход +2 оставляет 6. После ответа соперника 7 или 8; какой ход первого выигрывает в обоих случаях?','2','Из 7 добавить 2; из 8 тоже можно добавить 2, получим не меньше 9.'],['Куча 6, ходы +1/+2, цель 11. Первый добавляет 2, оставляя 8. После ответа соперника 9 или 10 какой ход выигрывает?','2','Из 9 добавить 2 до 11; из 10 достаточно добавить 1.']],
22:[['A и B параллельны, длятся 2 и 7 минут. C длится 3 минуты после обеих. Общее время?','10','C стартует на 7-й минуте и заканчивается на 10-й.'],['Две параллельные работы длятся 4 и 6 минут; затем работа 5 минут. Общее время?','11','6+5=11.']],
23:[['Пути A→B=2, B→D=5, A→C=4, C→D=1. Кратчайшая длина A→D?','5','Через C: 4+1=5; через B: 7.'],['A→B=3, B→D=2, A→C=1, C→D=8. Найди кратчайшую длину.','5','Через B: 3+2=5.']],
24:[['Найди максимальную серию A в строке AAABAA.','3','Самая длинная серия — первые три A.'],['Найди максимальную серию B в строке ABBBAABBBB.','4','Последняя серия B имеет длину 4.']],
25:[['Сколько положительных делителей у 48?','10','48=2⁴×3; число делителей (4+1)(1+1)=10.'],['Сколько положительных делителей у 36?','9','Делители: 1,2,3,4,6,9,12,18,36.']],
26:[['Интервалы [1,2],[2,4],[4,6],[3,5]. Максимум непересекающихся занятий?','3','Берём первые три: [1,2],[2,4],[4,6].'],['Интервалы [0,3],[1,2],[2,4],[4,5]. Максимум непересекающихся?','3','Можно взять [1,2],[2,4],[4,5].']],
27:[['Две группы точек: в первой 3 точки, во второй 5. Каков размер наибольшего кластера?','5','Сравни размеры кластеров: максимум 5.'],['Три группы содержат 2,4 и 3 точки. Размер крупнейшего кластера?','4','Наибольшая группа содержит 4 точки.']]
};

const key='egeProgress2027-v1';
let state=loadState(); let activeFilter='Все темы'; let activeTask=1; let teacherMode=false;let examSession=state.exam||null;
function loadState(){try{return JSON.parse(localStorage.getItem(key))||{tasks:{},note:''}}catch{return {tasks:{},note:''}}}
function save(){state.exam=examSession;localStorage.setItem(key,JSON.stringify(state));renderStats();renderList();if(document.querySelector('#progress-view').classList.contains('hidden')===false)renderProgress()}
function normalize(s){return String(s??'').trim().toLowerCase().replace(/[₀₁₂₃₄₅₆₇₈₉]/g,'').replace(/\s+/g,'').replace(/^\+/,'').replace(/ё/g,'е')}
function record(n){return state.tasks[n]||(state.tasks[n]={attempts:0,correct:false,confidence:'',verified:false,note:''})}
function renderStats(){const vals=Object.values(state.tasks);const viewed=vals.filter(v=>v.attempts||v.confidence||v.verified).length;const correct=vals.filter(v=>v.correct).length;const independent=vals.filter(v=>v.confidence==='independent').length;const review=vals.filter(v=>v.confidence==='review').length;document.querySelector('#stat-viewed').innerHTML=`${viewed} <small>/ 27</small>`;document.querySelector('#stat-correct').textContent=correct;document.querySelector('#stat-independent').textContent=independent;document.querySelector('#stat-review').textContent=review;document.querySelector('#hero-done').textContent=viewed;document.querySelector('#hero-independent').textContent=`${independent} уверенно`;document.querySelector('#hero-needs').textContent=`${review} повторить`;document.querySelector('#hero-bar').style.width=`${viewed/27*100}%`}
function renderFilters(){document.querySelector('#filters').innerHTML=topics.map(t=>`<button class="filter ${t===activeFilter?'active':''}" data-filter="${t}">${t}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;renderFilters();renderList()})}
function visibleTasks(){const q=document.querySelector('#search').value.trim().toLowerCase();return tasks.filter(t=>(activeFilter==='Все темы'||t.g===activeFilter)&&(!q||`${t.n} ${t.t} ${t.g}`.toLowerCase().includes(q)))}
function renderList(){const list=document.querySelector('#task-list');list.innerHTML=visibleTasks().map(t=>{const r=record(t.n);return `<button class="task-item ${activeTask===t.n?'active':''}" data-n="${t.n}"><span class="task-no">${String(t.n).padStart(2,'0')}</span><span class="task-name">${t.t}<span class="task-meta">${t.g}</span></span><i class="status-dot ${r.correct?'correct':r.confidence==='review'?'review':''}"></i></button>`}).join('')||'<p class="empty-state">По такому запросу пока ничего нет.</p>';list.querySelectorAll('.task-item').forEach(b=>b.onclick=()=>{activeTask=Number(b.dataset.n);renderList();renderTask();document.querySelector('#task-panel').scrollIntoView({behavior:'smooth',block:'nearest'})})}
function renderTask(){const t=tasks.find(x=>x.n===activeTask)||tasks[0];const r=record(t.n);const checked=r.attempts>0;const isCorrect=r.correct;document.querySelector('#task-panel').innerHTML=`<div class="task-topline"><span>ЗАДАНИЕ ${String(t.n).padStart(2,'0')} · 1 БАЛЛ</span><span class="tag">${t.g}</span></div><h3>${t.t}</h3><p class="task-prompt">${t.p}</p><details class="task-hint"><summary>Небольшая подсказка</summary><p>${t.h}</p></details><div class="answer-row"><input id="answer-input" type="text" autocomplete="off" placeholder="Твой ответ" aria-label="Ответ"><button id="check-answer" class="button primary">Проверить</button></div><div id="feedback" class="feedback ${checked?(isCorrect?'ok':'no'):''}" aria-live="polite">${checked?(isCorrect?'Верно! Хорошая работа.':'Пока не совпало. Посмотри решение и попробуй объяснить шаг.') : ''}</div>${checked||teacherMode?`<div class="solution"><strong>Разбор</strong><br>${t.s}</div>`:''}<details class="python-block"><summary>Как решить это кодом</summary><pre>${escapeHtml(t.c)}</pre></details><div class="reflection"><span>Как получилось решить?</span><button class="confidence ${r.confidence==='independent'?'selected':''}" data-value="independent">Самостоятельно</button><button class="confidence ${r.confidence==='help'?'selected':''}" data-value="help">С подсказкой</button><button class="confidence ${r.confidence==='review'?'selected':''}" data-value="review">Нужно повторить</button></div><div class="teacher-only teacher-check"><label><input type="checkbox" id="verified" ${r.verified?'checked':''}> Ученица объяснила решение своими словами</label><textarea class="note-input" id="task-note" rows="2" placeholder="Заметка по этому номеру">${escapeHtml(r.note||'')}</textarea></div>`;
document.querySelector('#check-answer').onclick=()=>{const value=document.querySelector('#answer-input').value;const ok=normalize(value)===normalize(t.a);r.attempts++;r.correct=ok;save();renderTask()};document.querySelector('#answer-input').onkeydown=e=>{if(e.key==='Enter')document.querySelector('#check-answer').click()};document.querySelectorAll('.confidence').forEach(b=>b.onclick=()=>{r.confidence=b.dataset.value;save();renderTask()});if(document.querySelector('#verified'))document.querySelector('#verified').onchange=e=>{r.verified=e.target.checked;save()};if(document.querySelector('#task-note'))document.querySelector('#task-note').oninput=e=>{r.note=e.target.value;save()}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function examQuestion(t,remedial=false){return {base:t.n,title:t.t,group:t.g,prompt:t.p,answer:t.a,solution:t.s,remedial,submitted:false,ok:null}}
function makeRemedials(t){return remedialBank[t.base].map(([p,a,s])=>({base:t.base,title:t.title,group:t.group,prompt:p,answer:a,solution:s,remedial:true,submitted:false,ok:null}))}
function beginExam(){examSession={queue:tasks.map(t=>examQuestion(t)),index:0,first:{},right:0,wrong:0,wrongTotal:0,added:0,wrongTopics:{},complete:false};document.querySelector('#exam-intro').classList.add('hidden');document.querySelector('#exam-result').classList.add('hidden');document.querySelector('#exam-active').classList.remove('hidden');save();renderExam()}
function renderExam(){
 const intro=document.querySelector('#exam-intro'),active=document.querySelector('#exam-active'),result=document.querySelector('#exam-result');
 if(!examSession){intro.classList.remove('hidden');active.classList.add('hidden');result.classList.add('hidden');document.querySelector('#start-exam').classList.remove('hidden');document.querySelector('#resume-exam').classList.add('hidden');return}
 if(examSession.complete||examSession.index>=examSession.queue.length){examSession.complete=true;intro.classList.remove('hidden');active.classList.add('hidden');result.classList.remove('hidden');document.querySelector('#start-exam').classList.remove('hidden');document.querySelector('#resume-exam').classList.add('hidden');renderExamResult();return}
 intro.classList.remove('hidden');document.querySelector('#start-exam').classList.toggle('hidden',true);document.querySelector('#resume-exam').classList.remove('hidden');active.classList.remove('hidden');result.classList.add('hidden');
 const q=examSession.queue[examSession.index],answered=examSession.index+1,total=examSession.queue.length;
 document.querySelector('#exam-counter').textContent=`Задание ${answered} из ${total}${q.remedial?' · дополнительное по теме':''}`;
 document.querySelector('#exam-score').textContent=`Верно с первого раза: ${examSession.right}/27 · Ошибок: ${examSession.wrongTotal}`;
 document.querySelector('#exam-bar').style.width=`${Math.min(100,examSession.index/total*100)}%`;
 document.querySelector('#exam-panel').innerHTML=`<div class="exam-question-label">${q.remedial?'ДОПОЛНИТЕЛЬНАЯ ЗАДАЧА':'ЭКЗАМЕН · №'+String(q.base).padStart(2,'0')} · ${escapeHtml(q.group)}</div><h3>${escapeHtml(q.title)}</h3><p class="task-prompt">${escapeHtml(q.prompt)}</p>${q.submitted?`<div class="exam-feedback ${q.ok?'ok':'no'}" aria-live="polite">${q.ok?'Ответ принят.':'Ответ не совпал.'}${!q.ok?` Добавлены две задачи по теме «${escapeHtml(q.group)}»; они будут после этого вопроса.`:''}</div>`:`<div class="answer-row"><input id="exam-answer" type="text" autocomplete="off" placeholder="Впиши ответ" aria-label="Ответ на экзаменационное задание"><button id="exam-submit" class="button primary">Ответить</button></div><p class="exam-tip">Подсказки и разбор откроются после завершения экзамена.</p>`}<div class="exam-actions">${q.submitted?'<button id="exam-next" class="button primary">Следующее задание</button>':''}</div>`;
 if(!q.submitted){const submit=()=>submitExamAnswer();document.querySelector('#exam-submit').onclick=submit;document.querySelector('#exam-answer').onkeydown=e=>{if(e.key==='Enter')submit()};document.querySelector('#exam-answer').focus()}else document.querySelector('#exam-next').onclick=nextExamQuestion;
}
function submitExamAnswer(){const q=examSession.queue[examSession.index];if(!q||q.submitted)return;const value=document.querySelector('#exam-answer').value.trim();if(!value){document.querySelector('#exam-answer').focus();return}q.submitted=true;q.ok=normalize(value)===normalize(q.answer);if(!q.remedial&&!Object.hasOwn(examSession.first,q.base)){examSession.first[q.base]=q.ok;if(q.ok)examSession.right++;else{examSession.wrong++;examSession.wrongTopics[q.group]=(examSession.wrongTopics[q.group]||0)+1}}if(!q.ok){examSession.wrongTotal++;const extras=makeRemedials(q);examSession.queue.splice(examSession.index+1,0,...extras);examSession.added+=extras.length}save();renderExam()}
function nextExamQuestion(){examSession.index++;if(examSession.index>=examSession.queue.length)examSession.complete=true;save();renderExam()}
function renderExamResult(){const wrong=Object.entries(examSession.wrongTopics);const topicsList=wrong.length?wrong.map(([g,n])=>`<li>${escapeHtml(g)} — ${n} ошибок в основных заданиях</li>`).join(''):'<li>Ошибок в основных заданиях нет.</li>';document.querySelector('#exam-result').innerHTML=`<p class="eyebrow">РЕЗУЛЬТАТЫ</p><h3>Экзамен завершён</h3><div class="exam-result-score">${examSession.right} / 27</div><p>Верно с первой попытки по основным заданиям. Всего ошибок с учётом дополнительных: ${examSession.wrongTotal}. Добавлено тренировочных задач: ${examSession.added}.</p><h4>Темы для разбора</h4><ul>${topicsList}</ul><p>Ответы и пояснения можно открыть в разделе «Практика», где они доступны после проверки.</p><button id="exam-again" class="button primary">Пройти новый экзамен</button>`;document.querySelector('#exam-again').onclick=beginExam}
function renderProgress(){const groups=[...new Set(tasks.map(t=>t.g))];document.querySelector('#topic-progress').innerHTML=groups.map(g=>{const set=tasks.filter(t=>t.g===g),done=set.filter(t=>record(t.n).confidence==='independent'||record(t.n).verified).length;return `<div class="topic-row"><span>${escapeHtml(g)}</span><div class="topic-meter"><i style="width:${done/set.length*100}%"></i></div><small>${done}/${set.length}</small></div>`}).join('');const todo=tasks.filter(t=>record(t.n).confidence==='review'||(record(t.n).attempts&&!record(t.n).correct));document.querySelector('#review-list').innerHTML=todo.length?todo.map(t=>`<a class="review-link" href="#practice" data-open="${t.n}"><b>${String(t.n).padStart(2,'0')}</b><span>${escapeHtml(t.t)}</span></a>`).join(''):'<p class="empty-state">Пока нет отмеченных пробелов. Отметьте «Нужно повторить» после разбора сложного номера.</p>';document.querySelectorAll('[data-open]').forEach(a=>a.onclick=()=>{activeTask=Number(a.dataset.open);showView('practice');renderList();renderTask()});document.querySelector('#lesson-note').value=state.note||'';const e=examSession;document.querySelector('#exam-progress-summary').innerHTML=e?`<strong>${e.complete?'Завершён':'В процессе'}</strong><p>Правильных с первой попытки: ${e.right}/27 · ошибок: ${e.wrongTotal} · добавлено дополнительных задач: ${e.added}</p>${Object.keys(e.wrongTopics).length?`<p>Повторить: ${Object.entries(e.wrongTopics).map(([g,n])=>`${escapeHtml(g)} (${n})`).join(', ')}</p>`:''}`:'<p class="empty-state">Экзамен пока не проходили.</p>'}
function showView(which){document.querySelector('#practice-view').classList.toggle('hidden',which!=='practice');document.querySelector('#progress-view').classList.toggle('hidden',which!=='progress');document.querySelector('#exam-view').classList.toggle('hidden',which!=='exam');document.querySelectorAll('.nav-link[data-view]').forEach(a=>a.classList.toggle('active',a.dataset.view===which));if(which==='progress')renderProgress();if(which==='exam')renderExam()}
document.querySelectorAll('.nav-link[data-view]').forEach(a=>a.onclick=e=>{e.preventDefault();showView(a.dataset.view)});document.querySelector('#start-exam').onclick=beginExam;document.querySelector('#resume-exam').onclick=renderExam;document.querySelector('#mode-toggle').onclick=()=>{teacherMode=!teacherMode;document.body.classList.toggle('teacher-mode',teacherMode);document.querySelector('#mode-toggle').textContent=teacherMode?'Режим: преподаватель':'Режим: ученица';renderTask()};document.querySelector('#mode-toggle').textContent='Режим: ученица';document.querySelector('#search').oninput=renderList;document.querySelector('#hero-date').textContent=new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date());document.querySelector('#save-note').onclick=()=>{state.note=document.querySelector('#lesson-note').value;localStorage.setItem(key,JSON.stringify(state));document.querySelector('#note-saved').textContent='Сохранено';setTimeout(()=>document.querySelector('#note-saved').textContent='',1800)};document.querySelector('#export-btn').onclick=()=>{const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='progress-ege-informatika.json';a.click();URL.revokeObjectURL(a.href)};document.querySelector('#import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const imported=JSON.parse(await f.text());if(!imported.tasks)throw new Error();state={tasks:imported.tasks,note:imported.note||'',exam:imported.exam||null};examSession=state.exam;localStorage.setItem(key,JSON.stringify(state));renderStats();renderList();renderTask();renderProgress();renderExam();alert('Отчёт загружен.')}catch{alert('Не получилось прочитать этот файл прогресса.')}};document.querySelector('#reset-btn').onclick=()=>{if(confirm('Сбросить прогресс и заметки на этом устройстве?')){state={tasks:{},note:'',exam:null};examSession=null;localStorage.setItem(key,JSON.stringify(state));renderStats();renderList();renderTask();renderProgress();renderExam()}};
if(examSession&&!examSession.complete){document.querySelector('#start-exam').classList.add('hidden');document.querySelector('#resume-exam').classList.remove('hidden')}
renderFilters();renderStats();renderList();renderTask();

